name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run build

      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  upload-release-asset:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: List dist contents
        run: ls -R /home/runner/work/render-lib  # Full path to the downloaded dist directory

      - name: Upload Release Asset to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/render-lib/render-lib/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
