name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run build

      - name: Verify dist folder
        run: ls -la dist  # This verifies that the dist folder is created and contains files


      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  upload-release-asset:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Upload Release Asset to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
